DB:
  MongoDB:
    Debian: ⚠️
    openSUSE: ⚠️
    openEuler: ⚠️
    Deepin: ⚠️
  mariadb(Mysql):
    Arch Linux: ✅ mariadb-10.9.3-1
    Debian: ✅ mariadb-1:10.6.8
    Gentoo: ✅ mysql-8.0.27
    openKylin: ✅ mysql-8.0
    openSUSE: ⚠️
    Ubuntu: mysql-server-8.0.30
    OpenBSD: ⚠️
    openEuler: ✅ mariadb-10.5.16
    Deepin: ✅ mysql-server-8.0.29-1
  postgresql:
    Arch Linux: ✅ postgresql-14.5-2
    Debian: ✅ postgresql-14.5
    Gentoo: ✅ postgresql-14.5
    openKylin: ✅ postgresql-12.2
    openSUSE: ✅ postgresql-14.5
    Ubuntu: ✅ postgresql-14+238
    OpenBSD: ⚠️
    openEuler: ⚠️
    Deepin: postgresql-14-14.1-1
  sqlite:
    Anolis: ✅
    Arch Linux: ✅ sqlite-3.39.4-1
    Debian: ✅ sqlite-2.8.17
    Gentoo: ✅ sqlite-3.39.3
    openKylin: ✅ sqlite-3.31.1
    openSUSE: ✅ sqlite-3.39.3
    Ubuntu: ✅ sqlite3-3.37.2-2
    OpenBSD: ✅ sqlite3-3.39.3
    openEuler: ✅ sqlite-3.36.0
    Deepin: sqlite3-3.36.0-2
http/web 服务器:
  Apache2:
    Arch Linux: ✅ apache-2.4.54-2
    Debian: ✅ apache-2.4.54
    Gentoo: ✅ apache-2.4.54
    openSUSE: ✅ apache-22.4.54
    Ubuntu: ✅ apache2-2.4.52-1ubuntu4.1
    openEuler: ⚠️
    Deepin: apache2-2.4.51-2
  HAProxy:
    Ubuntu: ✅ haproxy 2.4.18-0ubuntu1
    OpenBSD: ⚠️
    openEuler: ✅ haproxy-2.2.16
    Deepin: ⚠️
  Lighttpd:
    Debian: ✅ lighttpd-1.4.67
    Gentoo: ✅ lighttpd-1.4.67
    openSUSE: ✅ lighttpd-1.4.66
    Ubuntu: ✅ lighttpd 1.4.63-1ubuntu3
    OpenBSD: ⚠️
    openEuler: ✅ lighttpd-1.4.53
    Deepin: ⚠️
  Nginx:
    Arch Linux: ✅ nginx-1.22.1-1
    Debian: ✅ nginx-1.22.0
    Fedora: ✅ nginx-1.23.1
    openSUSE: ✅ nginx-1.23.1
    Ubuntu: ✅ nginx-1.18.0-6ubuntu14.2
    OpenBSD: ⚠️
    openEuler: ✅ nginx-1.21.5
    Deepin: ⚠️
    FreeBSD: ✅ nginx-1.20.2
  Squid:
    Debian: ✅ squid-5.6
    Gentoo: ✅ squid-5.4.1
    openSUSE: ✅ squid-5.7
    Ubuntu: ✅ squid-5.2-1ubuntu4.1
    OpenBSD: ⚠️
    openEuler: ⚠️
    Deepin: ⚠️
  Tengine:
    Debian:
    openEuler: ⚠️
    Deepin: ⚠️
  Varnish:
    Debian: ✅ varnish-7.1.1
    Ubuntu: ✔️ varnish 6.6.1-1ubuntu0.2
    OpenBSD: ⚠️
    openEuler: ⚠️
    Deepin: ⚠️
web:
  flask:
    Arch Linux: ✅ python-flask-2.2.2-1
    openEuler: ✅ python-flask-1.1.2
    Deepin: python3-flask-2.0.1-2
中间件:
  Dubbo:
    openEuler: ⚠️
    Deepin: ⚠️
  MemCache:
    Debian: ✅ libmemcached-1.0.18
    Gentoo: ✅ memcached-1.6.17
    Ubuntu: ✅ memcached-1.6.14-1
    OpenBSD: ⚠️
    openEuler: ✅ memcached-1.6.12
    Deepin: ✔️ memcached-1.6.12
  Redis:
    Alpine: ✅ redis-7.0.5
    Arch Linux: redis-7.0.5-1
    Debian: ✅ redis-7.0.5
    Gentoo: ✅ redis-7.0.5
    openSUSE: ✅ redis-7.0.5
    FreeBSD: ✅ redis-6.2.6
    OpenBSD: ⚠️
    openEuler: ✅ redis-6.0.11
    Deepin: redis-server-5:6.0.16-1
  mybatis:
    openEuler: ⚠️
    Deepin: ⚠️
  numpy:
    Arch Linux: python-numpy-1.23.4-1
    Debian: ✅ numpy-1:1.21.5
    Gentoo: ✅ numpy-1.23.3
    OpenBSD: ✅ py3-numpy-1.23.2
    openEuler: ✅ numpy-1.21.4
    Deepin: ⚠️
  scipy:
    Debian: ✅ scipy-1.8.1
    Gentoo: ✅ scipy-1.9.1
    OpenBSD: ⚠️
    openEuler: ✅ scipy-1.6.2
    Deepin: ⚠️
  zookeeper:
    Debian: ✅ zookeeper-3.8.0
    Ubuntu: ✔️ zookeeper-bin-3.4.13-6ubuntu4
    openEuler: ⚠️
    Deepin: ⚠️
其他:
  
